# Generated by Django 5.0.2 on 2024-02-22 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('moderator_username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('moderator_lname', models.CharField(max_length=20)),
                ('moderator_fname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_ID', models.IntegerField()),
                ('Team_Name', models.CharField(max_length=30)),
                ('Wins', models.IntegerField()),
                ('Losses', models.IntegerField()),
                ('Team_Rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('player_in_game_name', models.CharField(max_length=20)),
                ('player_fname', models.CharField(max_length=20)),
                ('player_lname', models.CharField(max_length=20)),
                ('player_dc_id', models.CharField(max_length=15)),
                ('player_fc', models.CharField(max_length=14)),
                ('Team_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplatourneyApp.team')),
            ],
        ),
    ]
