# Generated by Django 5.0.2 on 2024-02-22 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplatourneyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_checkin_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_rank',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_role',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='Team_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SplatourneyApp.team'),
        ),
    ]
