# Generated by Django 5.0.2 on 2024-02-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplatourneyApp', '0002_player_player_checkin_status_player_player_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_checkin_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_role',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
