# Generated by Django 4.1.7 on 2024-04-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SplatourneyApp", "0002_moderator_moderator_password"),
    ]

    operations = [
        migrations.RemoveField(model_name="bracket", name="tournament_title",),
        migrations.RemoveField(model_name="bracketcolumn", name="bracket_ID",),
        migrations.RemoveField(model_name="gameentry", name="pairing_ID",),
        migrations.RemoveField(model_name="gameentry", name="team_ID",),
        migrations.DeleteModel(name="Moderator",),
        migrations.RemoveField(model_name="pairing", name="bracketColumn_ID",),
        migrations.RemoveField(model_name="player", name="Team_ID",),
        migrations.RemoveField(model_name="playerrole", name="player_ID",),
        migrations.DeleteModel(name="Schedule",),
        migrations.DeleteModel(name="Bracket",),
        migrations.DeleteModel(name="BracketColumn",),
        migrations.DeleteModel(name="GameEntry",),
        migrations.DeleteModel(name="Pairing",),
        migrations.DeleteModel(name="Player",),
        migrations.DeleteModel(name="PlayerRole",),
        migrations.DeleteModel(name="Team",),
        migrations.DeleteModel(name="Tournament",),
    ]
