# Generated by Django 5.0.2 on 2024-02-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplatourneyApp', '0003_alter_player_player_checkin_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
