# Generated by Django 5.0.2 on 2024-02-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplatourneyApp', '0004_alter_player_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_rank',
            field=models.CharField(max_length=5),
        ),
    ]
