# Generated by Django 5.0.2 on 2024-02-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplatourneyApp', '0006_alter_player_player_dc_id_alter_player_player_fc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
