# Generated by Django 5.0.2 on 2024-02-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplatourneyApp', '0007_alter_player_player_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_rank',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
