# Generated by Django 5.0.2 on 2024-02-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplatourneyApp', '0008_alter_player_player_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.CharField(default='member', max_length=10, null=True),
        ),
    ]
