# Generated by Django 5.0.3 on 2024-04-01 17:09

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplatourneyApp', '0009_alter_player_player_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_ID', models.IntegerField()),
                ('bracket_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_ID', models.IntegerField()),
                ('time_Start', models.TimeField()),
                ('time_End', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_title', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('tournament_description', models.CharField(max_length=300)),
                ('tournament_mode', models.CharField(max_length=6)),
                ('registration_status', models.CharField(max_length=18)),
                ('tournament_status', models.CharField(max_length=12)),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Losses',
            new_name='losses',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Team_ID',
            new_name='team_ID',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Team_Name',
            new_name='team_Name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Team_Rank',
            new_name='team_Rank',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Wins',
            new_name='wins',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='moderator_fname',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='moderator_lname',
        ),
        migrations.CreateModel(
            name='BracketColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracketColumn_ID', models.IntegerField()),
                ('bracketColumn_Name', models.CharField(max_length=20)),
                ('bracketColumn_Limit', models.IntegerField()),
                ('bracket_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplatourneyApp.bracket')),
            ],
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairing_ID', models.IntegerField()),
                ('pairing_Name', models.CharField(max_length=20)),
                ('pairing_Status', models.CharField(max_length=11)),
                ('bracket_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplatourneyApp.bracket')),
            ],
        ),
        migrations.CreateModel(
            name='GameEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_Check_in_Status', models.CharField(max_length=11)),
                ('game_Result', models.CharField(max_length=4)),
                ('team_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplatourneyApp.team')),
                ('pairing_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplatourneyApp.pairing')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_role', models.CharField(max_length=20)),
                ('player_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplatourneyApp.player')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bracket',
            name='tournament_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplatourneyApp.tournament'),
        ),
    ]
